# Generated by Django 2.1.2 on 2018-10-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
